/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ppc_tp1_choco.view;

import java.awt.Color;
import java.awt.Graphics;
import java.util.Hashtable;
import java.util.List;

/**
 *
 * @author Red
 */
public class Panel extends javax.swing.JTabbedPane {

    List<Triplet> triples;
    List<String>[] colors;
    
    public Panel() {
        initComponents();
    }
    
    public Panel(List<Triplet> t, List<String>[] c)
    {
        initComponents();
        triples = t;
        colors  = c;
    }
    
    public void printTriple(Triplet t, Graphics g, int x, int y)
    {
        for(int c=0 ; c<colors.length ; c++)
        {
            if(c == 0)
            {
                g.setColor(Color.RED);
            }
            else if(c == 1)
            {
                g.setColor(Color.BLUE);
            }
            else
            {
                g.setColor(Color.BLACK);
            }
            for(int i=0 ; i<colors[c].size() ; i++)
            {
                if(t.a == Integer.parseInt(colors[c].get(i)))
                {
                    g.drawString("("+t.a, x, y);
                }
                if(t.b == Integer.parseInt(colors[c].get(i)))
                {
                    g.drawString("      "+t.b, x, y);
                }
                if(t.c == Integer.parseInt(colors[c].get(i)))
                {
                    g.drawString("            "+t.c+")", x, y);
                }
            }
        }
    }
    
    @Override
    public void paint(Graphics g)
    {
        super.paint(g);
        int x = 10;
        int y = 30;
        for(int i=1 ; i<triples.size() ; i++)
        {
            printTriple(triples.get(i), g,x,y);
            y += 20;
            if(i%20 == 0)
            {
                x += 90;
                y = 30;
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 396, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 296, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
